package ovh.wiktormalyska.pharmacysystembackend.pharmacy;

public enum PharmacyType {
  APTEKA_OGOLNODOSTEPNA,
  PUNKT_APTECZNY,
  APTEKA_SZPITALNA,
  APTEKA_ZAKLADOWA,
  DZIAL_FARMACJI_SZPITALNEJ,
  APTEKA_SZPITALNA_BEZ_ZGODY,
  APTEKA_ZAKLADOWA_MON,
  APTEKA_ZAKLADOWA_MON_BEZ_ZGODY,
  DZIAL_FARMACJI_SZPITALNEJ_MON,
  APTEKA_ZAKLADOWA_BEZ_ZGODY
}
